import Header from "@/components/Header";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  slider,
}: {
  children: React.ReactNode;
  slider: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen">
          <Header></Header>
          <main className=" flex flex-row">
            <section
              className="w-1/5 scrollbar-hide"
              style={{
                height: "calc(100vh - 56px)",
              }}
            >
              {slider}
            </section>
            <section className="w-4/5 h-full">{children}</section>
          </main>
        </div>
      </body>
    </html>
  );
}
